### ISSUE TITLE
[NestCam]Failed to request access token. Unexpected API Error - 405

### ISSUE THREAD

**Issue by cbeale** [KhaosT/homebridge-nest-cam#40]
Hi -

Having an issue with NestCam, trying to add it to my existing homebridge setup.

Homebridge starts up and then I get

"[NestCam]Failed to request access token. Unexpected API Error - 405"

I added it as shown in the guide.

Is this known?  I saw one person comment about it but no resolution was given.

Thanks

**Comment by The-Exalted** [comment]
Hi there, having the same issue. Also can't add cameras as accessories in home app. 

Novice user here (just started today) but thankful for help.

**Comment by iandronowicz** [comment]
Worked like charm for more than 5 months, stopped working since yesterday. Restarted homebridge a couple of times but no luck: I think it has something to do with the plugin authentication with near. Something must have changed in the API.

**Comment by felsmann** [comment]
Glad I jumped on here before I started tinkering, same issue here

**Comment by morilm** [comment]
HI

Same error here

[NestCam]Failed to request access token. Unexpected API Error - 405

**Comment by KhaosT** [comment]
The API probably changed recently. I can take a look this weekend.

**Comment by coxfrederic** [comment]
My camera's stopped updating, I'm not getting any errors but I can only assume it is a general issue, thanks @KhaosT for taking a look at it.

**Comment by landocarlesien** [comment]
I have the same error

**Comment by NajibNour** [comment]
Same here!!

**Comment by OkiRules** [comment]
Hey KhaosT,

Having the same issue... When will this be fixed? (when is your weekend) as I love this and would love to keep using it!

Thanks in advance.

**Comment by QandnotU** [comment]
Same. Glad I came here before I started dismantling Homebridge in the quest to fix.

**Comment by cbeale** [comment]
thanks.

im getting 

"{"url":"/session","message":"400 Bad Request"}curl: (6) Could not resolve host:" from the curl command however

**Comment by KhaosT** [comment]
did you copy the whole thing correctly?

**Comment by cbeale** [comment]
nm. it worked to get token on the pi.  was getting that error on macos.

**Comment by harryohalloran** [comment]
How do I handle a password to generate the token if I have an “!” in my password?  Looks like it’s not working correctly due to the character.

**Comment by KhaosT** [comment]
I tried with `!` and it's working for me... if not, try use `%21` in place where it suppose to be `!`

**Comment by cbeale** [comment]
I got it added to homebridge and it added the camera as a motion sensor.  How can I add it so it shows up with other cameras and displays the video?

Thanks so much for your work!

**Comment by KhaosT** [comment]
@cbeale if you go to Home app, add new accessory, the camera should show up?

**Comment by OkiRules** [comment]
Where did you put the "!" mark?

**Comment by harryohalloran** [comment]
Strange, after I enter the email and pass with the ! in the pass, here is what I get:

     --data-urlencode “password=passwordpriortotheexclamationpointhomebridge -Ipasswordaftertheexclamationpoint"
{"error":"access_denied","error_description":"invalid user credentials","instance_id":"a97454fe-5a72-43e6-871d-2a874cd94ec6"}

**Comment by OkiRules** [comment]
where do you put the "!" mark???

**Comment by KhaosT** [comment]
@harryohalloran I'm confused, where is that `-l` coming from? the full command should be something like `curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email=a@b.com" --data-urlencode "password=blabla!!!!123"`

**Comment by OkiRules** [comment]
where do you put the "!" mark???
I can see if it works

**Comment by NajibNour** [comment]
Works like a charm no issues with (0.0.12 update)

**Comment by cbeale** [comment]
@KhaosT I removed the bridge from my phone and re added it.  All 13 accessories connected to the homebridge added/configured themselves and the camera only adds itself as a motion detector and not as a camera.

**Comment by KhaosT** [comment]
@cbeale if it's configured properly, you should see a separate camera accessory in there. If it's not showing up for you, please open a separate issue so we don't spam everyone else in the thread.

![image](https://user-images.githubusercontent.com/1725664/50049550-d9c56000-009c-11e9-90e3-4ae26de6d351.png)

**Comment by harryohalloran** [comment]
All good, looks like a specific combination of characters I had in my password was causing the issue.  Changed the password and got it working correctly.

**Comment by black01gt** [comment]
Thanks everything works great now.

**Comment by KhaosT** [comment]
@black01gt Huh this is interesting... I'm not seeing the `expires_in` for `access_token` for account with 2FA enabled, and I'm not exactly sure if there is a way to refresh access token automatically... Please report back if this stop working after the expiration date.

**Comment by black01gt** [comment]
I don't have 2FA enabled. Should I enable it and get a new token?

**Comment by KhaosT** [comment]
If you hate manually refresh token every month, maybe give that a try?

**Comment by black01gt** [comment]
Thanks again. all set.

**Comment by iandronowicz** [comment]
I cannot get the token with 2fa enabled: I get {"status":"INVALID_INFO"}

**Comment by iandronowicz** [comment]
Never mind: it was character error, I was copying and pasting the code in Notes, and it changed the " char to another thing... I got the access token now, but Homebridge crashes and says:

ERROR LOADING PLUGIN homebridge-nest-cam:
[12/16/2018, 1:50:21 AM] Error: Cannot find module './Hello.js'

**Comment by iandronowicz** [comment]
again, if anyone finds the same errors as me: I tried uninstalling the nom package and re installing it. It wouldn't install with sudo (as I always do it) I tried without sudo and it worked.

WORKING, thanks!!

**Comment by Rens93** [comment]
[NestCam]Failed to request access token. Unexpected API Error - 403

When I use the code in terminal I get the next error:

{"url":"/session","message":"400 Bad Request"}/homebridge #

**Comment by morilm** [comment]
All working fine with 0.12 version...

I have used the curl command on this post as the one in the github didn't worked for me.

**Comment by waxlabo** [comment]
I got the access_token but I am not sure how to read it?  Does it end before / or "?

**Comment by waxlabo** [comment]
Oh nevermind. I was copying the wrong access_token all along.

**Comment by coxfrederic** [comment]
So we have to do this every month? I also had the issue with "!" and %21 didn't work for me, so I just changed my password to get the access token.

**Comment by coxfrederic** [comment]
This is not working for me. I added my access token without and afterwards with 2FA but both are not working. I'm not getting any errors ... what can be wrong? I get an access token returned but it does not seem to be valid

**Comment by coxfrederic** [comment]
Do I need a Nest API developer account or something?

**Comment by coxfrederic** [comment]
My access token is something like "b.10587059.OunaLccXhsEYERTYKK2341Kn4XRwnINSTbraPK0468PImYEJhUZoCr3kpSpxwaFU3l9jMDtkdcU7WACHANGEDSOMECHARS5WHhRHYqmOpik"

**Comment by KhaosT** [comment]
@coxfrederic can you create an new issue in this project and post log homebridge print at start?

**Comment by QandnotU** [comment]
After updating the plugin and copying the access code in my config, I'm still getting the 405 error. I'm seeing two access tokens being returned, I'm assuming it's the first one?

**Comment by rgury** [comment]
Love this plugin.  Dying to get it back up.  Unable to get token, I have 2FA.

When I paste command into terminal:

 curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email=XXYY@gmail.com" --data-urlencode "password=XXYY"

In return I receive: 

curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email= XXYY@gmail.com" --data-urlencode "password= XXYY"platform": "Nest-cam",

**Comment by QandnotU** [comment]
I've updated the plugin and regenerated the token and added it to the config. All looks good in Homebridge, but I'm having trouble adding the camera back in. Any tips and tricks would be greatly appreciated.

**Comment by KhaosT** [comment]
@QandnotU can you create a new issue in this project and post log homebridge print there?

**Comment by felsmann** [comment]
> [NestCam]Failed to request access token. Unexpected API Error - 403
> 
> When I use the code in terminal I get the next error:
> 
> {"url":"/session","message":"400 Bad Request"}/homebridge #

I am having this issue as well, how did you resolve it?

**Comment by Rens93** [comment]
I didn’t ☹️

**Comment by morilm** [comment]
> > [NestCam]Failed to request access token. Unexpected API Error - 403
> > When I use the code in terminal I get the next error:
> > {"url":"/session","message":"400 Bad Request"}/homebridge #
> 
> I am having this issue as well, how did you resolve it?

Use the curl expresion provided above... the one on the github doesn't work for me

You just need to put your email address and your nest password

curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email=a@b.com" --data-urlencode "password=blabla!!!!123"

**Comment by djglisson2** [comment]
I saw it mentioned above, but not sure it was ever resolved: When a password ends in a ! (as mine did) it results in : -bash: !": event not found

The only way around this seems to be changing one's password to not end in a ! (which I did). Would be lovely if that wasn't required however.

**Comment by haroldsdesk** [comment]
I have upgraded the plugin, was able to get a token using 2FA method and put it in the config but I still get [NestCam]Failed to request access token. Unexpected API Error - 405

I must be missing something...

Events with specific values removed:

curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email=MYEMAIL" --data-urlencode "password=MYPASSWORD"

_{"status":"VERIFICATION_PENDING","2fa_token":"2FATOKENVALUE","truncated_phone_number":"5555"}_

curl -X "POST" "https://home.nest.com/api/0.1/2fa/verify_pin" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/json; charset=utf-8' -d $'{"pin": "555555","2fa_token": "2FATOKENVALUE"}'

_{"status":"ID_MATCH_POSITIVE","access_token":"TOKENVALUE"}_

CONFIG:

{
  "platform": "Nest-cam",
  "access_token": "TOKENVALUE",
  "useOMX": false
}

**Comment by felsmann** [comment]
Likely your plugin is not updated 

Juan Felsmann 
jfelsmann@gmail.com

On Dec 22, 2018, at 08:03, Harold <notifications@github.com> wrote:

I have upgraded the plugin, was able to get a token using 2FA method and put it in the config but I still get [NestCam]Failed to request access token. Unexpected API Error - 405

I must be missing something...

Events with specific values removed:

curl -X "POST" "https://home.nest.com/session" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "email=MYEMAIL" --data-urlencode "password=MYPASSWORD"

{"status":"VERIFICATION_PENDING","2fa_token":"2FATOKENVALUE","truncated_phone_number":"5555"}

curl -X "POST" "https://home.nest.com/api/0.1/2fa/verify_pin" -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' -H 'Content-Type: application/json; charset=utf-8' -d $'{"pin": "555555","2fa_token": "2FATOKENVALUE"}'

{"status":"ID_MATCH_POSITIVE","access_token":"TOKENVALUE"}

CONFIG:

{
"platform": "Nest-cam",
"access_token": "TOKENVALUE",
"useOMX": false
}

**Comment by applemacgenius** [comment]
I have tried this so many different ways.  I keep getting:
{"url":"/session","message":"400 Bad Request"}

I have not "!" in my password.  I have a "@" but I don't think that matters.

I did notice there is some new info on https://developers.nest.com/guides/api/authorization-reference
and https://developers.nest.com/guides/api/how-to-auth

any help would be appreciated.

**Comment by JoshCash** [comment]
I'm having the same exact issue as applemacgenius. No clue where to go from here sadly.

**Comment by asmodeus097** [comment]
I am able to request a token using the first curl sequence and I do receive my SMS message code. When I try to send the second curl command to verify I receive {"error":"access_denied","error_description":"permission denied","instance_id":...

**Comment by cobyalmond** [comment]
> Hi -
> 
> Having an issue with NestCam, trying to add it to my existing homebridge setup.
> 
> Homebridge starts up and then I get
> 
> "[NestCam]Failed to request access token. Unexpected API Error - 405"
> 
> I added it as shown in the guide.
> 
> Is this known? I saw one person comment about it but no resolution was given.
> 
> Thanks

Having same Issue. Tried all the steps. I'm wondering if using the homebridge-nest plugin causes a conflict. Any ideas?

**Comment by black01gt** [comment]
I’m yawing the homebridge nest plugin also with no issues. Everything is working great. Make sure you follow the steps closely.

**Comment by coxfrederic** [comment]
> I am able to request a token using the first curl sequence and I do receive my SMS message code. When I try to send the second curl command to verify I receive {"error":"access_denied","error_description":"permission denied","instance_id":...

Did you resolve this? I'm getting the same. Even through postman nor curl can I get a token based on the verification PIN and token from previous command..

**Comment by asmodeus097** [comment]
Still unresolved. I ended up having to turn off 2 factor authentication to get it to work.

**Comment by wasifhuda** [comment]
For those who have a "!" at the end of a password, and trying to run the command which results in the following error: !": event not found

Try running "set +H" in Terminal and then running curl express, it should fix the issue
